# Generated by Django 3.1.7 on 2021-05-14 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.TextField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('rate', models.CharField(choices=[('PG', 'PG'), ('PG13', 'PG-13'), ('G', 'G'), ('R', 'R')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slot', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default about text', max_length=200)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('age', models.IntegerField(default=0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
