# Generated by Django 3.1.7 on 2021-03-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
