# Generated by Django 3.1.7 on 2021-05-14 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('time', models.CharField(choices=[('8h', '8:00'), ('11h', '11:00'), ('14h', '14:00'), ('17h', '17:00'), ('20h', '20:00')], default='8h', max_length=4)),
                ('date', models.DateField()),
                ('slot', models.IntegerField(default=0, null=True)),
                ('type', models.CharField(choices=[('2D', '2D'), ('3D', '3D')], max_length=4)),
                ('status', models.CharField(choices=[('ON', 'Active'), ('OFF', 'Inactive')], default='OFF', max_length=4)),
                ('movie', models.ForeignKey(default='MV00001', on_delete=django.db.models.deletion.CASCADE, to='system.movie')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.room')),
                ('user', models.ForeignKey(default='MV00001', on_delete=django.db.models.deletion.CASCADE, to='system.dashboard')),
            ],
            options={
                'unique_together': {('room', 'time')},
            },
        ),
    ]
