# Generated by Django 3.1.7 on 2021-05-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20210515_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('ON', 'Active'), ('OFF', 'Inactive')], default='ON', max_length=4),
        ),
    ]
