# Generated by Django 3.1.7 on 2021-06-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20210518_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='confirm_code',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='confirmed',
            field=models.CharField(choices=[('ON', 'Active'), ('OFF', 'Inactive')], default='ON', max_length=4),
        ),
    ]
