# Generated by Django 3.1.7 on 2021-06-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20210610_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='confirmed',
            field=models.CharField(choices=[('ON', 'Active'), ('OFF', 'Inactive')], default='OFF', max_length=4),
        ),
    ]
